export class Routes {
  static readonly ONBOARDING: string = 'pages/OnboardingPage';
  static readonly HOME: string = 'pages/Index';
  static readonly DIVINATION: string = 'pages/DivinationPage';
  static readonly RESULT: string = 'pages/DivinationResultPage';
  static readonly DAILY_FORTUNE: string = 'pages/DailyFortunePage';
  static readonly DIVINATION_HISTORY: string = 'pages/DivinationHistoryPage';
}
